"""Record of one LLM transport round-trip, for observability.

One row per call to an LLM transport: start_new_chat, send, or
send_tool_results. Written by the instrumented transport wrapper
the instant the underlying call returns or raises, independent of
whatever session the calling service is mid-transaction on.

Independent on purpose. A turn that calls the LLM and then fails to
parse the response rolls its own work back, but the call still
happened and still cost latency and money. The record of it has to
survive that rollback, so the wrapper writes through its own
session and commits before handing control back. This is the
deliberate opposite of error_log, which shares the service session
and commits all-or-nothing with the turn.

session_id is nullable by design. The wrapper sees only a transport
handle, never a session id, so calls are not linked to sessions at
write time. Evaluation and diagnostic calls legitimately have no
session. Cross-linking happens later through trace_id, once trace
context is propagated through the turn path.
"""

from __future__ import annotations

from sqlalchemy import Enum as SQLEnum
from sqlalchemy import Float, ForeignKey, Index, Integer, String, Text
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import Base, Timestamps, UUIDPrimaryKey
from app.models.enums import TransportKind


class LLMCall(Base, UUIDPrimaryKey, Timestamps):
    """One LLM transport round-trip.

    Carries timing, size, token, and cost data for a single call,
    plus a success flag and an error message when the call raised.
    trace_id groups calls belonging to one logical operation and is
    the join key to sessions and to error_log once trace context is
    propagated.
    """

    __tablename__ = "llm_call"

    # Composite index for the admin browse: filter by transport,
    # order by recency. created_at comes from Timestamps. Declared
    # here so autogenerate sees it in model metadata and does not
    # try to drop it from the live DB.
    __table_args__ = (Index("ix_llm_call_transport_created", "transport_kind", "created_at"),)

    # Best-effort link to the session that triggered the call. Null
    # for eval and diagnostic calls, and for any call made before
    # trace propagation can attribute it. SET NULL so deleting a
    # session does not delete its observability history.
    session_id: Mapped[str | None] = mapped_column(
        String(36),
        ForeignKey("session.id", ondelete="SET NULL"),
        nullable=True,
        default=None,
    )

    # Groups calls belonging to one logical operation. Generated by
    # the wrapper per round-trip for now, becomes the shared join
    # key once turns carry the same id.
    trace_id: Mapped[str] = mapped_column(String(36), nullable=False, index=True)

    # Which transport and which Protocol method this row records.
    # method is one of start_new_chat, send, send_tool_results. The
    # pair (transport_kind, method) is the stable span name: a finite,
    # queryable set with no per-call-site naming. method is a free-form
    # string, not an enum: the closed set tracks the Protocol and an
    # observability write column needs no validation.
    transport_kind: Mapped[TransportKind] = mapped_column(
        SQLEnum(TransportKind, native_enum=False, length=32),
        nullable=False,
    )
    method: Mapped[str] = mapped_column(String(32), nullable=False)

    # Model identifier as the transport reported it. Free-form:
    # claude.ai has no model id we control, DeepSeek reports one.
    # Null when the transport exposes nothing useful.
    model: Mapped[str | None] = mapped_column(String(64), nullable=True, default=None)

    # Wall-clock duration of the round-trip in milliseconds, measured
    # around the underlying transport call.
    latency_ms: Mapped[int] = mapped_column(Integer, nullable=False)

    # Character lengths of the prompt sent and the response received.
    # Cheap to capture, useful before token counts exist. response
    # length is 0 when the call raised before a response.
    prompt_chars: Mapped[int] = mapped_column(Integer, nullable=False)
    response_chars: Mapped[int] = mapped_column(Integer, nullable=False)

    # Token counts. Populated from the API response when the transport
    # reports them (DeepSeek), null otherwise. Estimation lands later.
    prompt_tokens: Mapped[int | None] = mapped_column(Integer, nullable=True, default=None)
    completion_tokens: Mapped[int | None] = mapped_column(Integer, nullable=True, default=None)

    # Estimated cost in USD. Recorded for aggregation but gates no
    # decision. Null when the model's pricing is unknown.
    cost_usd: Mapped[float | None] = mapped_column(Float, nullable=True, default=None)

    # False when the underlying transport call raised. error carries
    # the message in that case, null on success.
    success: Mapped[bool] = mapped_column(nullable=False)
    error: Mapped[str | None] = mapped_column(Text, nullable=True, default=None)

    def __repr__(self) -> str:
        return (
            f"<LLMCall transport={self.transport_kind.value!r} "
            f"method={self.method!r} success={self.success!r}>"
        )
