"""initial schema

Revision ID: db8dabc9fef6
Revises:
Create Date: 2026-04-25 03:58:03.473948+00:00
"""

from collections.abc import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "db8dabc9fef6"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "domain",
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "LANGUAGE",
                "FRAMEWORK",
                "LIBRARY",
                "CONCEPT",
                "TOOL",
                "PRACTICE",
                "OTHER",
                name="domainkind",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("description", sa.String(length=512), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "teaching_preference",
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "topic",
        sa.Column("path", sa.String(length=512), nullable=False),
        sa.Column("domain", sa.String(length=64), nullable=False),
        sa.Column("parent_id", sa.String(length=36), nullable=True),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column(
            "difficulty",
            sa.Enum(
                "BEGINNER",
                "INTERMEDIATE",
                "ADVANCED",
                name="difficulty",
                native_enum=False,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column("prerequisites", sa.JSON(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "NOT_STARTED",
                "IN_PROGRESS",
                "LEARNED",
                "NEEDS_REVISION",
                name="topicstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("last_reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["parent_id"], ["topic.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("path"),
    )
    with op.batch_alter_table("topic", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_topic_domain"), ["domain"], unique=False)

    op.create_table(
        "user_knowledge_assertion",
        sa.Column("topic_path", sa.String(length=512), nullable=False),
        sa.Column(
            "difficulty",
            sa.Enum(
                "BEGINNER",
                "INTERMEDIATE",
                "ADVANCED",
                name="difficulty",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "source",
            sa.Enum(
                "SELF_DECLARED",
                "DERIVED_FROM_LEARNED_ITEMS",
                "RESUME",
                "JD",
                name="assertionsource",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("user_knowledge_assertion", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_user_knowledge_assertion_topic_path"), ["topic_path"], unique=False
        )

    op.create_table(
        "user_profile",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("default_stack", sa.String(length=64), nullable=True),
        sa.Column("resume_text", sa.Text(), nullable=True),
        sa.Column("target_jd_text", sa.Text(), nullable=True),
        sa.Column("chrome_profile_path", sa.String(length=1024), nullable=True),
        sa.Column("prereq_warning_dismissed", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "session",
        sa.Column("topic_id", sa.String(length=36), nullable=True),
        sa.Column(
            "mode_used",
            sa.Enum(
                "FLASHCARD",
                "TYPE_THE_ANSWER",
                "CODE_WITH_EXPLANATION",
                "MULTIPLE_CHOICE",
                "EXPLAIN_BACK",
                "SOCRATIC",
                name="learningmode",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "state",
            sa.Enum(
                "IN_PROGRESS",
                "COMPLETED",
                "ABANDONED",
                "ARCHIVED",
                name="sessionstate",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("claude_chat_url", sa.String(length=512), nullable=True),
        sa.Column("claude_chat_message_count", sa.Integer(), nullable=False),
        sa.Column("parent_session_id", sa.String(length=36), nullable=True),
        sa.Column("active_preferences", sa.JSON(), nullable=False),
        sa.Column("context_snapshot", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["parent_session_id"], ["session.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["topic_id"], ["topic.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "error_log",
        sa.Column("session_id", sa.String(length=36), nullable=True),
        sa.Column("kind", sa.String(length=128), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("context", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["session_id"], ["session.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("error_log", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_error_log_session_id"), ["session_id"], unique=False)

    op.create_table(
        "learned_item",
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("topic_id", sa.String(length=36), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("answer", sa.Text(), nullable=False),
        sa.Column("your_answer", sa.Text(), nullable=True),
        sa.Column(
            "mode",
            sa.Enum(
                "FLASHCARD",
                "TYPE_THE_ANSWER",
                "CODE_WITH_EXPLANATION",
                "MULTIPLE_CHOICE",
                "EXPLAIN_BACK",
                "SOCRATIC",
                name="learningmode",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "difficulty",
            sa.Enum(
                "BEGINNER",
                "INTERMEDIATE",
                "ADVANCED",
                name="difficulty",
                native_enum=False,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "LEARNED", "NEEDS_REVISION", name="learneditemstatus", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column("last_reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["session_id"], ["session.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["topic_id"], ["topic.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "session_turn",
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("turn_index", sa.Integer(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("CLAUDE", "USER", "SYSTEM", name="turnrole", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("raw_content", sa.Text(), nullable=False),
        sa.Column("parsed", sa.JSON(), nullable=True),
        sa.Column(
            "mode",
            sa.Enum(
                "FLASHCARD",
                "TYPE_THE_ANSWER",
                "CODE_WITH_EXPLANATION",
                "MULTIPLE_CHOICE",
                "EXPLAIN_BACK",
                "SOCRATIC",
                name="learningmode",
                native_enum=False,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["session_id"], ["session.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id", "turn_index", name="uq_session_turn_order"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("session_turn")
    op.drop_table("learned_item")
    with op.batch_alter_table("error_log", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_error_log_session_id"))

    op.drop_table("error_log")
    op.drop_table("session")
    op.drop_table("user_profile")
    with op.batch_alter_table("user_knowledge_assertion", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_knowledge_assertion_topic_path"))

    op.drop_table("user_knowledge_assertion")
    with op.batch_alter_table("topic", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_topic_domain"))

    op.drop_table("topic")
    op.drop_table("teaching_preference")
    op.drop_table("domain")
    # ### end Alembic commands ###
