"""add error_log trace_id

Revision ID: 307d0aaa8206
Revises: e458b1620327
Create Date: 2026-05-30 15:38:18.348707+00:00
"""

from collections.abc import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "307d0aaa8206"
down_revision: Union[str, None] = "e458b1620327"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("error_log", sa.Column("trace_id", sa.String(length=36), nullable=True))
    op.create_index(op.f("ix_error_log_trace_id"), "error_log", ["trace_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_error_log_trace_id"), table_name="error_log")
    op.drop_column("error_log", "trace_id")
    # ### end Alembic commands ###
