"""add llm_call table

Revision ID: e458b1620327
Revises: 79329541d3ad
Create Date: 2026-05-30 05:38:19.221768+00:00
"""

from collections.abc import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e458b1620327"
down_revision: Union[str, None] = "79329541d3ad"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "llm_call",
        sa.Column("session_id", sa.String(length=36), nullable=True),
        sa.Column("trace_id", sa.String(length=36), nullable=False),
        sa.Column(
            "transport_kind",
            sa.Enum(
                "CLAUDE_PLAYWRIGHT", "DEEPSEEK", name="transportkind", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column("method", sa.String(length=32), nullable=False),
        sa.Column("model", sa.String(length=64), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("prompt_chars", sa.Integer(), nullable=False),
        sa.Column("response_chars", sa.Integer(), nullable=False),
        sa.Column("prompt_tokens", sa.Integer(), nullable=True),
        sa.Column("completion_tokens", sa.Integer(), nullable=True),
        sa.Column("cost_usd", sa.Float(), nullable=True),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["session_id"], ["session.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_llm_call_trace_id"), "llm_call", ["trace_id"], unique=False)
    op.create_index(
        "ix_llm_call_transport_created", "llm_call", ["transport_kind", "created_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_llm_call_transport_created", table_name="llm_call")
    op.drop_index(op.f("ix_llm_call_trace_id"), table_name="llm_call")
    op.drop_table("llm_call")
    # ### end Alembic commands ###
