"""Database engine and session factory.

The engine is created once per process. Sessions are short-lived and
created per unit of work; in the API layer each request gets its own
session via FastAPI's dependency injection.

This module deliberately define only the primitives. Models live in
app.models. Migration live in alembic/.
"""

from collections.abc import Generator

from sqlalchemy import Engine, create_engine
from sqlalchemy.orm import DeclarativeBase, Session, sessionmaker

from app.core.config import get_settings


class Base(DeclarativeBase):
    """Declaratative base class for all ORM models

    Every model in app.models inherits form this. Having a single Base
    lets Alembic discover models for autogenerated migrations.
    """


def _build_engine() -> Engine:
    """Construct the SQLAlchemy engine from current settings.

    Separated from module-level initialisation so tests can reconstruct
    the engine against a different database by clearing the settings
    cache and calling _build_engine() again
    """
    settings = get_settings()

    connect_args: dict[str, object] = {}
    if settings.database_url.startswith("sqlite"):
        # SQLite forbids sharing a connection across threads by default.
        # FastAPI may use multiple threads, so relax this. Safe for our
        # single-writer usage pattern.
        connect_args["check_same_thread"] = False

    return create_engine(settings.database_url, connect_args=connect_args, echo=False, future=True)


engine: Engine = _build_engine()

SessionLocal: sessionmaker[Session] = sessionmaker(
    bind=engine,
    autoflush=False,
    autocommit=False,
    expire_on_commit=False,
)


def get_db() -> Generator[Session]:
    """Yield a database session for the duration of a request.

    Used as a FastAPI dependency. The session is closed automatically
    when the request handler returns, whether or not an exception was
    raised.
    """
    session = SessionLocal()
    try:
        yield session
    finally:
        session.close()
